### ISSUE TITLE
Make Server API CORS configurable

### ISSUE THREAD

**Issue by alisonrag** [zhad3/zrenderer#19]
i'm planning to use zrenderer API in a different ip/port than front-end

if i make a request from chrome using axios i receive this error:
![image](https://user-images.githubusercontent.com/10372732/151885308-0f11895a-85e9-46d1-954a-073203d983d5.png)

adding the following code to `getAccessTokens` and other handler functions fixed my issue:
`res.headers.addField("Access-Control-Allow-Origin", "*");`

i was not able to find a better place

so i suggest to add a option in `zrenderer.conf` to allow CORS

**Comment by zhad3** [comment]
Hey, seems simple enough to be implemented. Thank you for testing it upfront. I'll add it when I have time.

**Comment by alisonrag** [comment]
also while i was testing i saw that modern frontend frameworks do a first request with "OPTION header" to check CORS and available methods:
![image](https://user-images.githubusercontent.com/10372732/152012895-d18ae549-bb6e-4c38-b669-2c25d61600ce.png)

i fixed this by adding a generic handler function:
server/package.d:
```
router.post("/render", &handleRenderRequest);
router.any("/render", &handleOptions);
```

server/routes/render.d:
```
void handleOptions(HTTPServerRequest req, HTTPServerResponse res) @trusted
{
    res.headers.addField("Access-Control-Allow-Origin", "*");
    res.headers.addField("Access-Control-Allow-Methods", "PUT, POST, DELETE, GET, OPTIONS");
    res.headers.addField("Access-Control-Allow-Headers", "Origin, X-Requested-With, Accept, Authorization, Content-Type");
    res.statusCode = HTTPStatus.ok;
    res.writeVoidBody();
}
``` 

reference:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#functional_overview

**Comment by zhad3** [comment]
@alisonrag I have made changes which allow you to enable CORS and set origins from which the requests may be made from.

However please note that I advice not allowing direct access to the `/render` API. While I have implemented the accesstoken system to somewhat allow direct access the available rights are not fledged out yet. For example if you were to implement a public frontend API then the users will also be able to make whatever request they want. They could for example set the job ids to `"0-30000"` which will essentially tell the server to render all monsters, npc and players that exist while also setting the canvas to something huge like `2147483647x2147483647+0+0`. Spam these requests and the harddisk of your server will be full really fast as well as unresponsive.

For the admin API it should be fine (as long as you keep your admin tokens safe). Allow setting TLS is also something that still needs to be done so that requests are done through HTTPS. Currently I have the server behind nginx which would take care of that.

**Comment by alisonrag** [comment]
confirm that it is working:
![image](https://user-images.githubusercontent.com/10372732/152660027-e3832b59-0a5a-43a0-af3b-ab07ab19e28f.png)

**Comment by alisonrag** [comment]
thanks for the advice, i'm thinking about add a limit to requests and also limit the number of jobs and canvas size
