### ISSUE TITLE
Wrong image size output

### ISSUE THREAD

**Issue by alisonrag** [zhad3/zrenderer#22]
i cant find a reason, but using this config:
```
{
    "gender": 1,
    "job": [
        "4075"
    ],
    "head": 1,
    "headPalette": 1,
    "headdir": 0,
    "headgear": [
        586,
        1602,
        25
    ],
    "garment": 98,
    "bodyPalette": 0,
    "action": 3
}
```

image result will be:
![image](https://user-images.githubusercontent.com/10372732/158406242-e3cbb0d1-aa4a-482b-9018-630ecfa65607.png)

a lot of extra space at image bottom

**Comment by alisonrag** [comment]
maybe should be the same reason of this:
```
{
    "gender": 1,
    "job": [
        "4068"
    ],
    "head": 1,
    "headPalette": 1,
    "headdir": 0,
    "headgear": [
        1884,
        0,
        1045
    ],
    "garment": 61,
    "bodyPalette": 0,
    "action": 0
}

```

output:
![image](https://user-images.githubusercontent.com/10372732/158408555-4cb8f639-bff1-4aae-b669-31e8fb8af58b.png)

**Comment by zhad3** [comment]
@alisonrag The first one is because the headgear `25` which is white beard has an offset of 300 pixels in the ACT file. They also make it transparent. This is a non-issue in-game because they are not bound to image dimensions as we are.

This can be fixed by not including sprites/sprite layers which are not visible because the alpha has been set to 0. For all other cases this cannot be fixed.

Regarding the second case that is another issue. It appears that Garments can also be animated... that is something I have not accounted for, or better said I haven't seen any.

**Comment by zhad3** [comment]
I have pushed a commit that adds support for animated garments:
![0](https://user-images.githubusercontent.com/6462844/158697323-2afaa6ed-ad4a-4cbc-8390-28c37ac3f9b2.png)

I also made the debug outlines optional now: https://github.com/zhad3/zrenderer#server-1. So that you can use the debug build for now (DMD release compilation still doesn't work)

**Comment by alisonrag** [comment]
> I have pushed a commit that adds support for animated garments
confirm that is working:
![8eabe6da-9507-49b9-b5c9-d443eccdb5b1](https://user-images.githubusercontent.com/10372732/158735869-139cdcf9-d661-429e-9a7c-0abca7446756.png)

**Comment by alisonrag** [comment]
since this is a issue with the sprite and not the zrenderer i'm closing.

thanks for your attention and time

**Comment by zhad3** [comment]
I have pushed another commit that will also address the first issue with the huge offset. Sprites that are invisible will now not be considered when calculating the image dimensions.
