### ISSUE TITLE
Can not render special costume/headgear effects

### ISSUE THREAD

**Issue by miixel2** [zhad3/zrenderer#29]
Hello,

   Just found that the application could not render some costume with following issues.

1. Does not in sprite id list.
2. The costume have some effect

 For example, Costume Spotlight
 
 Link: https://www.divine-pride.net/database/item/410127/costume-spotlight
 
 Do you have any advise to use or call some functions to render the costume with special effect added?

Best Regards

**Comment by zhad3** [comment]
Hi @miixel2 , TL;DR: It is currently not supported. Not just for costumes but also for headgears that use these effects.

I am aware of this feature but out-scoped it for the initial release because it requires a different rendering approach as is done currently with the sprites. I wanted to implement it at some point but didn't find the time and motivation to do it.

For some technical information: These effects are stored in `data/luafiles514/lua files/hateffectinfo/hateffectinfo.lub`.
The spotlight is defined as such:
```lua
HatEFID = {
  -- <snip>
  HAT_EF_C_Spot_Light = 174,
  -- <snip>
}
hatEffectTable = {
  -- <snip>
  [HatEFID.HAT_EF_C_Spot_Light] = {
    resourceFileName = "C_Spot_Light\\Spotlight.str",
    hatEffectPos = -6,
    hatEffectPosX = 0,
    isIgnoreRiding = true,
    isAdjustPositionWhenShrinkState = true,
    isAdjustSizeWhenShrinkState = true
  },
  -- <snip>
```
The table itself is easy to parse but it requires the rendering of `STR`  effects (see `C_Spot_Light\\Spotlight.str`) which is non-existant. Even if rendering itself would be done another issue would be on how to add these effects to the existing sprite in regards to frame count. zrenderer currently always chooses the frame count depending on the body sprite or animated headgears which are guaranteed to be in sync and end up in a perfect loop. The `STR` effects however do not adhere to that and selecting the least common denominator might not be feasible due to filesize. Hence I would prefer to simply cut off the `STR` effect and it starts repeating (ugly).

However, once `STR` effects are supported it would be as easy as to define these effects via an argument such as `--hateffect=174`.

**Comment by miixel2** [comment]
Hi @zhad3 , 
Thanks for explianation. 

I will waiting for the next release that support this ;)

**Comment by zhad3** [comment]
I did some base work on implementing this but then noticed that half of the hateffects are hardcoded inside the client executable. Truly a shame. I don't think its worthwhile to implement STR effect support for only a handful of hateffects.
Even less do I feel the need to somehow replicate the hardcoded effects.

Sorry but I will outscope this feature and close this ticket :'(

**Comment by reunite-ro** [comment]
https://github.com/MrAntares/roBrowserLegacy/pull/838/ I just saw RoBrowser implementing hateffects

**Comment by zhad3** [comment]
Hi @reunite-ro , as a foreword: roBrowser and zrenderer are very different projects. roBrowser is a game engine whereas zrenderer is an image generator. Just because it is done in roBrowser does not mean it can be copied over to zrenderer.

The link you posted also mentioned that only the effects that are not hard coded or have been manually replicated are supported.

I opened up the file again to check how many hard coded effects there are. In my (relatively old) version there are 140 hateffects and 88 out of those (62%) are hard coded.

I also found out that the connection between headgear/garment and hateffect does not necessarily need to be client side but can be sent from the server as part of the headgears stats.

For these headgears zrenderer has no way of knowing that they actually have a hateffect attached to them. zrenderer is 100% client side. For that to work you would need to actually copy the server data and incorporate it into zrenderer.

All in all, I still hold the previous sentiment that the effort required to support hateffects is not worth the effort.
