### ISSUE TITLE
Failed to compile on Ubuntu 18.04.6

### ISSUE THREAD

**Issue by tidre** [zhad3/zrenderer#32]
Hi,
I'm trying to compile zrenderer on Ubuntu 18.04.6 but I'm having trouble trying to do it.

Follow some informations:
OS
`Ubuntu LTS 18.04.6`

DUB
`DUB version 1.8.0-2, built on Mar 27 2018`

LDC / LDC2
`LDC - the LLVM D compiler (1.8.0): based on DMD v2.078.3 and LLVM 5.0.1`

OpenSSL
`OpenSSL 1.1.1  11 Sep 2018`

Command Line
`sudo dub build --compiler=ldc2 --build=release :server`

![image](https://github.com/zhad3/zrenderer/assets/17967697/09d8db0b-617b-4e53-a6e2-9fd5fa5c1054)

**Comment by tidre** [comment]
After uninstalling the libraries and installing again, it took a few steps but gave the error.

![image](https://github.com/zhad3/zrenderer/assets/17967697/e123c32b-60cc-403e-a323-f465e3491753)

**Comment by zhad3** [comment]
Hi @tidre unfortunately ubuntu 18 uses a too old version of dub and ldc.
I recommend downloading a newer version directly from the ldc release page: https://github.com/ldc-developers/ldc/releases

Assuming you're running x64 linux you would need to download something like `ldc2-1.32.2-linux-x86_64.tar.xz`.
In the provided archive you will find all the tools required under the `bin` directory.

If you run `dub` from that archive I believe you will have to add the `ldc2` executable to your `PATH` environment variable so that it can be picked it. For that to work you'll probably also need to uninstall your current dub and ldc2 which you got from the package manager.

Sorry for all the trouble but the D language and its tooling is sadly not very backwards compatible.

**Comment by tidre** [comment]
Hi @zhad3, 

Thank you for your help.
After updating ldc and dub my versions are:
 - LDC (1.24.0)
 - DUB (1.19.0)

But now I have the following problem:
![image](https://github.com/zhad3/zrenderer/assets/17967697/b49a66c9-f7ba-48e9-930d-e402671d97da)

**Comment by tidre** [comment]
After updating LDC, DUB, DMD, OpenSSL, still the error persists.

Versions:
![image](https://github.com/zhad3/zrenderer/assets/17967697/417ad9ed-2574-4194-9ad5-130ae6364438)

Error:
![Captura de tela 2023-07-12 000510](https://github.com/zhad3/zrenderer/assets/17967697/68eececa-cc1e-4756-9579-e3a0b901e2e1)

**Comment by carafelix** [comment]
I was having issues compiling. `curl -fsS https://dlang.org/install.sh | bash -s ldc` allowed me to compile successfully
