### ISSUE TITLE
Wrong background/transparency for custom mobs

### ISSUE THREAD

**Issue by EchoesOfMorroc** [zhad3/zrenderer#46]
I don't know what exactly causes this.
Some custom mobs have a wrong transparency when rendered:
![2038](https://github.com/user-attachments/assets/bf143cc2-719a-4cde-b383-76a265eaeae1)
![2037](https://github.com/user-attachments/assets/9192973f-4417-45c3-9a4f-7be85dd934ce)

But in game they work without any issue.

Here is an example (spr and act):
https://www.mediafire.com/file/a0q3rcp5c0qnmqy/parasite.rar/file

**Comment by zhad3** [comment]
Hi @EchoesOfMorroc 
Each sprite has a color palette consisting of exactly 256 colors.
Each color has 4 components: Red, Green, Blue and Alpha.

For the most part the Alpha component (indicating the transparency) has value `00` (meaning full transparent) for the background. In the sprites you have the value is `FF` (meaning full opaque).

This can be easily fixed. Guess I just forgot about that specific part because usually the color is always transparent in the sprite file.

**Comment by zhad3** [comment]
Fixed in v1.4.2
